# Generated by Django 3.2.25 on 2026-01-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['unit', 'status'], name='issues_issu_unit_id_e7a55c_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['unit', 'priority'], name='issues_issu_unit_id_dd5785_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['unit', 'status', 'priority'], name='issues_issu_unit_id_a0c9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['tenant', 'status'], name='issues_issu_tenant__182b17_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status', 'raised_date'], name='issues_issu_status_17a21f_idx'),
        ),
    ]
