# Generated by Django 3.2.25 on 2026-01-05 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique identifier for this content', max_length=100, unique=True)),
                ('block_type', models.CharField(choices=[('dashboard_welcome', 'Dashboard Welcome Message'), ('vacancy_alert', 'Vacancy Alert Message'), ('rent_reminder', 'Rent Reminder Message'), ('issue_notification', 'Issue Notification Message'), ('help_text', 'Help Text'), ('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy'), ('about', 'About Us'), ('custom', 'Custom Block')], default='custom', max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='HTML content allowed')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(help_text='HTML content allowed')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help Article',
                'verbose_name_plural': 'Help Articles',
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('rent_due', 'Rent Due Reminder'), ('rent_paid', 'Rent Payment Confirmation'), ('issue_raised', 'Issue Raised Notification'), ('issue_resolved', 'Issue Resolved Notification'), ('tenant_welcome', 'Tenant Welcome Message'), ('vacancy_alert', 'Vacancy Alert')], max_length=50, unique=True)),
                ('subject', models.CharField(help_text='Email subject or SMS prefix', max_length=200)),
                ('message', models.TextField(help_text='Use {{variable}} for dynamic content')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('max_buildings', models.IntegerField(blank=True, help_text='Null = unlimited', null=True)),
                ('max_units', models.IntegerField(blank=True, help_text='Null = unlimited', null=True)),
                ('max_users', models.IntegerField(default=1)),
                ('features', models.TextField(help_text='One feature per line')),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, help_text='Highlight this plan')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Smart PG & Flat Management CRM', max_length=200)),
                ('site_tagline', models.CharField(default='One dashboard to know everything about your property', max_length=255)),
                ('company_name', models.CharField(default='Property Management Co.', max_length=200)),
                ('company_email', models.CharField(default='info@example.com', max_length=200)),
                ('company_phone', models.CharField(default='+91 1234567890', max_length=20)),
                ('company_address', models.TextField(default='Your Company Address')),
                ('primary_color', models.CharField(default='#2563eb', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#64748b', help_text='Hex color code', max_length=7)),
                ('enable_tenant_portal', models.BooleanField(default=False, help_text='Allow tenants to login')),
                ('enable_sms_notifications', models.BooleanField(default=False)),
                ('enable_email_notifications', models.BooleanField(default=False)),
                ('auto_generate_rent', models.BooleanField(default=False, help_text='Auto-create rent entries each month')),
                ('rent_due_day', models.IntegerField(default=5, help_text='Day of month when rent is due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('footer_text', models.TextField(default='Built with ❤️ for Property Owners & Managers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StatusLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(choices=[('unit', 'Unit Status'), ('rent', 'Rent Status'), ('issue', 'Issue Status'), ('occupancy', 'Occupancy Status')], max_length=50)),
                ('code', models.CharField(help_text="Internal code (e.g., 'occupied', 'vacant')", max_length=50)),
                ('label', models.CharField(help_text='Display label', max_length=100)),
                ('color', models.CharField(default='#64748b', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Status Label',
                'verbose_name_plural': 'Status Labels',
                'ordering': ['status_type', 'order'],
                'unique_together': {('status_type', 'code')},
            },
        ),
    ]
