# Generated by Django 3.2.25 on 2026-01-08 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(default='edit', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddIndex(
            model_name='editingsession',
            index=models.Index(fields=['resource_type', 'resource_id'], name='common_edit_resourc_7cd7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='editingsession',
            index=models.Index(fields=['last_activity'], name='common_edit_last_ac_839bb8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='editingsession',
            unique_together={('resource_type', 'resource_id')},
        ),
    ]
