# Generated by Django 3.2.25 on 2026-01-10 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20260108_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpArticle',
        ),
        migrations.DeleteModel(
            name='PricingPlan',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_us',
            field=models.TextField(blank=True, help_text='About Us content (HTML allowed)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True, help_text='Contact address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email for support/inquiries', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_managers_per_owner',
            field=models.IntegerField(default=5, help_text='Maximum number of managers each owner can create. Set to 0 for unlimited.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_properties_per_owner',
            field=models.IntegerField(default=10, help_text='Maximum number of properties (buildings) each owner can add. Set to 0 for unlimited.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy',
            field=models.TextField(blank=True, help_text='Privacy Policy (HTML allowed)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_and_conditions',
            field=models.TextField(blank=True, help_text='Terms and Conditions (HTML allowed)'),
        ),
    ]
