# Generated by Django 3.2.25 on 2026-01-05 17:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occupancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expected rent amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('PARTIAL', 'Partial')], default='PENDING', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occupancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='occupancy.occupancy')),
            ],
            options={
                'verbose_name': 'Rent',
                'verbose_name_plural': 'Rents',
                'ordering': ['-month'],
                'unique_together': {('occupancy', 'month')},
            },
        ),
    ]
