# Generated by Django 3.2.25 on 2026-01-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rent',
            index=models.Index(fields=['occupancy', 'month'], name='rent_rent_occupan_3c92e4_idx'),
        ),
        migrations.AddIndex(
            model_name='rent',
            index=models.Index(fields=['occupancy', 'status'], name='rent_rent_occupan_32cab5_idx'),
        ),
        migrations.AddIndex(
            model_name='rent',
            index=models.Index(fields=['month', 'status'], name='rent_rent_month_7b8bce_idx'),
        ),
        migrations.AddIndex(
            model_name='rent',
            index=models.Index(fields=['occupancy', 'month', 'status'], name='rent_rent_occupan_f2a724_idx'),
        ),
    ]
