# Generated by Django 3.2.25 on 2026-01-08 15:10

import django.core.validators
from django.db import migrations, models
import rent.models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20260106_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Upload payment proof (receipt, screenshot, etc.)', null=True, upload_to=rent.models.rent_payment_proof_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
    ]
