# Generated by Django 3.2.25 on 2026-01-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['account', 'name'], name='tenants_ten_account_8215fc_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['account', 'phone'], name='tenants_ten_account_ce8769_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['account', 'created_at'], name='tenants_ten_account_2f2fef_idx'),
        ),
    ]
