# Generated by Django 3.2.25 on 2026-01-08 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tenants.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0002_auto_20260106_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('VOTER_ID', 'Voter ID'), ('POLICE_VERIFICATION', 'Police Verification'), ('RENT_AGREEMENT', 'Rent Agreement'), ('PHOTO', 'Photograph'), ('ADDRESS_PROOF', 'Address Proof'), ('EMPLOYMENT_PROOF', 'Employment Proof'), ('OTHER', 'Other Document')], max_length=30)),
                ('document_number', models.CharField(blank=True, help_text='Document ID/Number if applicable', max_length=50)),
                ('file', models.FileField(upload_to=tenants.models.tenant_document_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Document',
                'verbose_name_plural': 'Tenant Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenantdocument',
            index=models.Index(fields=['tenant', 'document_type'], name='tenants_ten_tenant__69ddaa_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdocument',
            index=models.Index(fields=['tenant', 'verification_status'], name='tenants_ten_tenant__b8bcba_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdocument',
            index=models.Index(fields=['verification_status'], name='tenants_ten_verific_314575_idx'),
        ),
    ]
