# Generated by Django 3.2.25 on 2026-01-05 17:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text="e.g., '203', 'PG-3'", max_length=50)),
                ('unit_type', models.CharField(choices=[('FLAT', 'Flat'), ('PG', 'PG')], max_length=10)),
                ('bhk_type', models.CharField(blank=True, help_text="e.g., '1BHK', '2BHK' (for flats)", max_length=10, null=True)),
                ('expected_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied')], default='VACANT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='accounts.account')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['unit_number'],
                'unique_together': {('building', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='PGRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text="e.g., 'Room 1', 'Room A'", max_length=20)),
                ('sharing_type', models.IntegerField(help_text='Number of beds: 1, 2, 3, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(limit_choices_to={'unit_type': 'PG'}, on_delete=django.db.models.deletion.CASCADE, related_name='pg_rooms', to='units.unit')),
            ],
            options={
                'verbose_name': 'PG Room',
                'verbose_name_plural': 'PG Rooms',
                'ordering': ['room_number'],
                'unique_together': {('unit', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(help_text="e.g., 'Bed 1', 'Bed A'", max_length=10)),
                ('status', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied')], default='VACANT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='units.pgroom')),
            ],
            options={
                'verbose_name': 'Bed',
                'verbose_name_plural': 'Beds',
                'ordering': ['bed_number'],
                'unique_together': {('room', 'bed_number')},
            },
        ),
    ]
