# Generated by Django 3.2.25 on 2026-01-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['room', 'status'], name='units_bed_room_id_edefd2_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['status'], name='units_bed_status_3789ae_idx'),
        ),
        migrations.AddIndex(
            model_name='pgroom',
            index=models.Index(fields=['unit'], name='units_pgroo_unit_id_2a4229_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['account', 'status'], name='units_unit_account_658404_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['account', 'unit_type'], name='units_unit_account_7edb30_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['building', 'status'], name='units_unit_buildin_f84676_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['account', 'building', 'status'], name='units_unit_account_56b586_idx'),
        ),
    ]
