# Generated by Django 3.2.25 on 2026-01-05 17:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agreement_document', models.FileField(blank=True, null=True, upload_to='agreements/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='units.bed')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='tenants.tenant')),
                ('unit', models.ForeignKey(blank=True, limit_choices_to={'unit_type': 'FLAT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='units.unit')),
            ],
            options={
                'verbose_name': 'Occupancy',
                'verbose_name_plural': 'Occupancies',
                'ordering': ['-start_date'],
            },
        ),
    ]
