# Generated by Django 3.2.25 on 2026-01-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='occupancy',
            index=models.Index(fields=['tenant', 'is_active'], name='occupancy_o_tenant__b6f5a4_idx'),
        ),
        migrations.AddIndex(
            model_name='occupancy',
            index=models.Index(fields=['unit', 'is_active'], name='occupancy_o_unit_id_cc1e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='occupancy',
            index=models.Index(fields=['bed', 'is_active'], name='occupancy_o_bed_id_b16a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='occupancy',
            index=models.Index(fields=['is_active', 'start_date'], name='occupancy_o_is_acti_951763_idx'),
        ),
        migrations.AddIndex(
            model_name='occupancy',
            index=models.Index(fields=['tenant', 'is_active', 'start_date'], name='occupancy_o_tenant__5df24d_idx'),
        ),
    ]
