# Generated by Django 3.2.25 on 2026-01-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0002_auto_20260106_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupancy',
            name='expected_checkout_date',
            field=models.DateField(blank=True, help_text='Expected date of checkout after notice period', null=True),
        ),
        migrations.AddField(
            model_name='occupancy',
            name='notice_date',
            field=models.DateField(blank=True, help_text='Date when tenant gave notice to vacate', null=True),
        ),
        migrations.AddField(
            model_name='occupancy',
            name='notice_reason',
            field=models.TextField(blank=True, help_text='Reason for leaving (optional)'),
        ),
    ]
