# Generated by Django 3.2.25 on 2026-01-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0003_auto_20260108_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupancy',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Mark as primary tenant. Only primary tenant gets rent records for shared flats.'),
        ),
    ]
