# Generated by Django 3.2.25 on 2026-01-07 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('GRANT_ACCESS', 'Grant Access'), ('REVOKE_ACCESS', 'Revoke Access'), ('PAY_RENT', 'Pay Rent'), ('ASSIGN_TENANT', 'Assign Tenant'), ('VACATE', 'Vacate')], db_index=True, help_text='Type of action performed', max_length=20)),
                ('resource_type', models.CharField(choices=[('Building', 'Building'), ('Unit', 'Unit'), ('PGRoom', 'PG Room'), ('Bed', 'Bed'), ('Tenant', 'Tenant'), ('Occupancy', 'Occupancy'), ('Rent', 'Rent'), ('Issue', 'Issue'), ('User', 'User'), ('Account', 'Account'), ('BuildingAccess', 'Building Access')], db_index=True, help_text='Type of resource affected', max_length=50)),
                ('resource_id', models.IntegerField(blank=True, db_index=True, help_text='ID of the resource affected', null=True)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from request', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('account', models.ForeignKey(help_text='Account this action belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.account')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'permissions': [('view_all_audit_logs', 'Can view all audit logs in account')],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['account', '-timestamp'], name='audit_audit_account_455e51_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'),
        ),
    ]
