# Generated by Django 3.2.25 on 2026-01-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['account', 'name'], name='buildings_b_account_6f8497_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['account', 'created_at'], name='buildings_b_account_396c1b_idx'),
        ),
    ]
