# Generated by Django 3.2.25 on 2026-01-07 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildings', '0002_auto_20260106_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(help_text='Building the manager can access', on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='buildings.building')),
                ('created_by', models.ForeignKey(blank=True, help_text='Owner who granted this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Manager who has access', on_delete=django.db.models.deletion.CASCADE, related_name='building_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Building Access',
                'verbose_name_plural': 'Building Accesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='buildingaccess',
            index=models.Index(fields=['user', 'building'], name='buildings_b_user_id_499f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingaccess',
            index=models.Index(fields=['building'], name='buildings_b_buildin_45ccb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='buildingaccess',
            unique_together={('user', 'building')},
        ),
    ]
