# Generated by Django 3.2.25 on 2026-01-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_auto_20260107_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='notice_period_days',
            field=models.IntegerField(default=30, help_text='Number of days notice required before checkout'),
        ),
    ]
